/**
 * Barcode/QR Code Scanner App
 * Digital Image Processing Course Project
 * Southern University of Science and Technology (SUSTech), 2026
 */

// ============ State ============
const state = {
    scanner: null,
    isScanning: false,
    scanFormat: 'all',       // 'all' | 'qr' | 'barcode'
    facingMode: 'environment',
    soundEnabled: true,
    history: [],
    currentResult: null,
};

// ============ Constants ============
const QR_FORMATS = [Html5QrcodeScanType.SCAN_TYPE_CAMERA];
const BARCODE_FORMATS = [
    'ean_13', 'ean_8', 'upc_a', 'upc_e',
    'code_128', 'code_39', 'code_93',
    'codabar', 'itf', 'rss_14', 'rss_expanded',
];

// ============ Test Images (generated by code/test-generator/generate_all.py) ============
const TEST_IMAGES = [
    // QR - Clean
    { src: '../../images/test_images/qr_clean_01.png', label: 'QR Clean 1' },
    { src: '../../images/test_images/qr_clean_02.png', label: 'QR Clean 2' },
    { src: '../../images/test_images/qr_clean_03.png', label: 'QR Clean 3' },
    // QR - Rotated
    { src: '../../images/test_images/qr_rotated_15_01.png', label: 'QR 15°' },
    { src: '../../images/test_images/qr_rotated_30_01.png', label: 'QR 30°' },
    { src: '../../images/test_images/qr_rotated_45_01.png', label: 'QR 45°' },
    // QR - Degraded
    { src: '../../images/test_images/qr_noisy_01.png', label: 'QR Noisy' },
    { src: '../../images/test_images/qr_blurred_01.png', label: 'QR Blurred' },
    { src: '../../images/test_images/qr_lighting_01.png', label: 'QR Uneven Light' },
    { src: '../../images/test_images/qr_complex_background.png', label: 'QR Complex BG' },
    // Barcodes
    { src: '../../images/test_images/barcode_ean13_01.png', label: 'EAN-13 1' },
    { src: '../../images/test_images/barcode_ean13_02.png', label: 'EAN-13 2' },
    { src: '../../images/test_images/barcode_ean13_rotated_15_01.png', label: 'EAN-13 15°' },
    { src: '../../images/test_images/barcode_code128_01.png', label: 'Code-128 1' },
    { src: '../../images/test_images/barcode_code128_02.png', label: 'Code-128 2' },
    { src: '../../images/test_images/barcode_code39_01.png', label: 'Code-39' },
    // Multi
    { src: '../../images/test_images/multi_qr_codes.png', label: 'Multiple QR' },
    { src: '../../images/test_images/mixed_barcode_qr.png', label: 'Mixed Types' },
];

// ============ Splash Screen ============
window.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => {
        document.getElementById('splash').classList.add('hide');
        document.getElementById('app').style.display = 'flex';
        init();
    }, 1500);
});

// ============ Initialization ============
function init() {
    loadHistory();
    renderGallery();
    setupTabs();
    setupButtons();
    setupFileInputs();
    setupSettings();
}

// ============ Tab Navigation ============
function setupTabs() {
    document.querySelectorAll('.tab-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            const tabId = 'tab-' + btn.dataset.tab;
            document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
            document.getElementById(tabId).classList.add('active');
            if (btn.dataset.tab === 'history') renderHistory();
            if (btn.dataset.tab === 'gallery') renderGallery();
        });
    });
}

// ============ Buttons ============
function setupButtons() {
    document.getElementById('btnStartScan').addEventListener('click', startScan);
    document.getElementById('btnStopScan').addEventListener('click', stopScan);
    document.getElementById('btnUpload').addEventListener('click', () => {
        document.getElementById('fileInput').click();
    });
    document.getElementById('btnCloseResult').addEventListener('click', () => {
        document.getElementById('resultCard').style.display = 'none';
    });
    document.getElementById('btnCopy').addEventListener('click', copyResult);
    document.getElementById('btnOpenUrl').addEventListener('click', openResultUrl);
    document.getElementById('btnSettings').addEventListener('click', openSettings);
    document.getElementById('btnCloseSettings').addEventListener('click', closeSettings);
    document.getElementById('btnClearHistory').addEventListener('click', clearHistory);
    document.getElementById('btnGalleryUpload').addEventListener('click', () => {
        document.getElementById('galleryFileInput').click();
    });

    // Settings modal backdrop
    document.querySelector('#settingsModal .modal-backdrop').addEventListener('click', closeSettings);
}

// ============ File Inputs ============
function setupFileInputs() {
    const fileInput = document.getElementById('fileInput');
    fileInput.addEventListener('change', (e) => {
        if (e.target.files.length > 0) {
            scanImageFile(e.target.files[0], 'resultCard', 'resultType', 'resultContent', 'resultConfidence');
            fileInput.value = '';
        }
    });

    const galleryInput = document.getElementById('galleryFileInput');
    galleryInput.addEventListener('change', (e) => {
        if (e.target.files.length > 0) {
            scanImageFile(e.target.files[0], 'galleryResultCard', null, null, null, true);
            galleryInput.value = '';
        }
    });
}

// ============ Camera Scanner ============
async function startScan() {
    try {
        document.getElementById('scanPlaceholder').style.display = 'none';
        document.getElementById('scanOverlay').style.display = 'flex';
        document.getElementById('btnStartScan').style.display = 'none';
        document.getElementById('btnStopScan').style.display = 'flex';

        const formatsToSupport = getScanFormats();
        const config = {
            fps: 10,
            qrbox: { width: 250, height: 250 },
            aspectRatio: 1,
            formatsToSupport: formatsToSupport,
        };

        // Configure based on scan format
        if (state.scanFormat === 'barcode') {
            config.qrbox = { width: 300, height: 150 };
        }

        state.scanner = new Html5Qrcode('reader');
        state.isScanning = true;

        await state.scanner.start(
            { facingMode: state.facingMode },
            config,
            onScanSuccess,
            onScanFailure
        );
    } catch (err) {
        console.error('Camera start error:', err);
        showToast('无法打开摄像头: ' + (err.message || '权限不足'));
        resetScanUI();
    }
}

function getScanFormats() {
    switch (state.scanFormat) {
        case 'qr':
            return [{ format: 'qr_code' }];
        case 'barcode':
            return BARCODE_FORMATS.map(f => ({ format: f }));
        case 'all':
        default:
            return [
                { format: 'qr_code' },
                ...BARCODE_FORMATS.map(f => ({ format: f })),
            ];
    }
}

function onScanSuccess(decodedText, decodedResult) {
    if (!state.isScanning) return;

    const formatName = decodedResult.result.format?.formatName || 'unknown';
    const type = formatName === 'qr_code' ? 'QR Code' : 'Barcode';

    // Play beep
    if (state.soundEnabled) playBeep();

    // Show result
    displayResult(decodedText, type, 'resultCard', 'resultType', 'resultContent', 'resultConfidence');

    // Save to history
    addToHistory(decodedText, type);

    // Brief pause to show result, then resume
    stopScan();
}

function onScanFailure(error) {
    // Scanning failures are normal (no barcode in view) — silent
}

async function stopScan() {
    if (state.scanner && state.isScanning) {
        try {
            await state.scanner.stop();
            state.scanner.clear();
        } catch (err) {
            console.warn('Scanner stop error:', err);
        }
        state.isScanning = false;
    }
    resetScanUI();
}

function resetScanUI() {
    document.getElementById('scanOverlay').style.display = 'none';
    document.getElementById('scanPlaceholder').style.display = 'flex';
    document.getElementById('btnStartScan').style.display = 'flex';
    document.getElementById('btnStopScan').style.display = 'none';
}

// ============ Image File Scanner ============
async function scanImageFile(file, cardId, typeId, contentId, confidenceId, isGallery = false) {
    showToast('正在识别...');

    try {
        const result = await decodeImageFile(file, state.scanFormat);

         if (result) {
            const card = document.getElementById(cardId);
            card.style.display = 'block';

            if (isGallery) {
                card.innerHTML = `
                    <div class="result-header">
                        <span class="badge ${result.type === 'QR Code' ? '' : 'barcode'}">${result.type}</span>
                        <span class="confidence">${result.confidence || ''}</span>
                        <button onclick="this.parentElement.parentElement.style.display='none'" class="icon-btn-sm">
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
                        </button>
                    </div>
                    <div class="result-content" style="font-size:16px;font-family:monospace;">${escapeHtml(result.text)}</div>
                    <div class="result-actions">
                        <button onclick="navigator.clipboard.writeText('${escapeHtml(result.text).replace(/'/g, "\\'")}');showToast('已复制')" class="btn-sm">复制</button>
                        ${isUrl(result.text) ? `<button onclick="window.open('${escapeHtml(result.text)}','_blank')" class="btn-sm">打开链接</button>` : ''}
                    </div>
                `;
            } else {
                document.getElementById(typeId).textContent = result.type;
                document.getElementById(typeId).className = 'badge ' + (result.type === 'QR Code' ? '' : 'barcode');
                document.getElementById(contentId).textContent = result.text;
                document.getElementById(confidenceId).textContent = result.confidence || '';
                document.getElementById('btnOpenUrl').style.display = isUrl(result.text) ? 'flex' : 'none';
             }
            addToHistory(result.text, result.type);
            if (state.soundEnabled) playBeep();
        } else {
            showToast('未识别到条码/二维码');
        }
    } catch (err) {
        console.error('Image scan error:', err);
        showToast('识别失败: ' + err.message);
    }
}

function loadImage(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => {
            const img = new Image();
            img.onload = () => resolve(img);
            img.onerror = () => reject(new Error('Image load error'));
            img.src = reader.result;
        };
        reader.onerror = () => reject(new Error('File read error'));
        reader.readAsDataURL(file);
    });
}

async function decodeImageFile(file, scanFormat) {
    const img = await loadImage(file);
    const canvas = document.createElement('canvas');
    canvas.width = img.width;
    canvas.height = img.height;
    const ctx = canvas.getContext('2d');
    ctx.drawImage(img, 0, 0);
    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);

    // 1) Try QR via jsQR
    if (scanFormat === 'all' || scanFormat === 'qr') {
        try {
            const qrCode = jsQR(imageData.data, imageData.width, imageData.height, {
                inversionAttempts: 'dontInvert',
            });
            if (qrCode && qrCode.data) {
                return { text: qrCode.data, type: 'QR Code', confidence: 'jsQR ✓' };
            }
        } catch {}
    }

    // 2) Try barcode via BarcodeDetector API (Chrome)
    if ((scanFormat === 'all' || scanFormat === 'barcode') && 'BarcodeDetector' in window) {
        try {
            const bd = new BarcodeDetector({
                formats: ['ean_13', 'ean_8', 'upc_a', 'upc_e', 'code_128', 'code_39', 'code_93', 'codabar', 'itf'],
            });
            const barcodes = await bd.detect(canvas);
            if (barcodes.length > 0) {
                return { text: barcodes[0].rawValue, type: 'Barcode', confidence: 'BarcodeDetector ✓' };
            }
        } catch {}
    }

    // 3) Try html5-qrcode file scan as fallback
    try {
        const tempId = 'temp-scan-' + Date.now();
        const div = document.createElement('div');
        div.id = tempId;
        div.style.display = 'none';
        document.body.appendChild(div);
        const fs = new Html5Qrcode(tempId);
        try {
            const result = await fs.scanFile(file, false);
            if (result && typeof result === 'string' && result.trim()) {
                return { text: result, type: 'Detected', confidence: 'html5-qrcode' };
            }
        } finally {
            try { await fs.clear(); } catch {}
            div.remove();
        }
    } catch {}

    return null;
}

// ============ Result Display ============
function displayResult(text, type, cardId, typeId, contentId, confidenceId) {
    document.getElementById(cardId).style.display = 'block';
    document.getElementById(typeId).textContent = type;
    document.getElementById(typeId).className = 'badge ' + (type === 'QR Code' ? '' : 'barcode');
    document.getElementById(contentId).textContent = text;
    document.getElementById(confidenceId).textContent = '';
    document.getElementById('btnOpenUrl').style.display = isUrl(text) ? 'flex' : 'none';
    state.currentResult = text;
}

function copyResult() {
    if (state.currentResult) {
        navigator.clipboard.writeText(state.currentResult).then(() => showToast('已复制到剪贴板'));
    }
}

function openResultUrl() {
    if (state.currentResult && isUrl(state.currentResult)) {
        window.open(state.currentResult, '_blank');
    }
}

// ============ Gallery ============
function renderGallery() {
    const grid = document.getElementById('galleryGrid');
    grid.innerHTML = TEST_IMAGES.map((img, idx) => `
        <div class="gallery-item" data-idx="${idx}">
            <img src="${img.src}" alt="${img.label}" loading="lazy"
                 onerror="this.parentElement.style.display='none'"
                 onload="this.parentElement.querySelector('.item-label').style.display='block'">
            <div class="item-label" style="display:none;">${img.label}</div>
        </div>
    `).join('');

    // Add click handlers
    grid.querySelectorAll('.gallery-item').forEach(item => {
        item.addEventListener('click', async () => {
            const idx = parseInt(item.dataset.idx);
            const imgData = TEST_IMAGES[idx];
            try {
                const resp = await fetch(imgData.src);
                const blob = await resp.blob();
                const file = new File([blob], imgData.src.split('/').pop(), { type: blob.type || 'image/png' });

                // Switch to scan tab to show result
                document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
                document.querySelector('.tab-btn[data-tab="scan"]').classList.add('active');
                document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
                document.getElementById('tab-scan').classList.add('active');

                scanImageFile(file, 'resultCard', 'resultType', 'resultContent', 'resultConfidence');
            } catch (err) {
                showToast('图片加载失败');
            }
        });
    });
}

// ============ History ============
function loadHistory() {
    try {
        const stored = localStorage.getItem('scan_history');
        state.history = stored ? JSON.parse(stored) : [];
    } catch {
        state.history = [];
    }
}

function saveHistory() {
    localStorage.setItem('scan_history', JSON.stringify(state.history.slice(0, 50)));
}

function addToHistory(text, type) {
    state.history.unshift({
        text,
        type,
        time: new Date().toLocaleString('zh-CN'),
    });
    if (state.history.length > 50) state.history.pop();
    saveHistory();
}

function renderHistory() {
    const list = document.getElementById('historyList');
    if (state.history.length === 0) {
        list.innerHTML = '<p class="empty-hint">暂无扫描记录</p>';
        return;
    }
    list.innerHTML = state.history.map(h => `
        <div class="history-item" onclick="navigator.clipboard.writeText('${escapeHtml(h.text).replace(/'/g, "\\'")}');showToast('已复制')">
            <span class="hi-type ${h.type === 'QR Code' ? 'qr' : 'barcode'}">${h.type}</span>
            <div class="hi-content">${escapeHtml(h.text)}</div>
            <div class="hi-time">${h.time}</div>
        </div>
    `).join('');
}

function clearHistory() {
    if (confirm('确定清空扫描历史？')) {
        state.history = [];
        saveHistory();
        renderHistory();
        showToast('历史已清空');
    }
}

// ============ Settings ============
function setupSettings() {
    document.getElementById('scanFormat').addEventListener('change', (e) => {
        state.scanFormat = e.target.value;
        localStorage.setItem('scan_format', state.scanFormat);
    });
    document.getElementById('cameraSelect').addEventListener('change', (e) => {
        state.facingMode = e.target.value;
    });
    document.getElementById('soundToggle').addEventListener('change', (e) => {
        state.soundEnabled = e.target.checked;
    });

    // Load saved
    const savedFormat = localStorage.getItem('scan_format');
    if (savedFormat) {
        state.scanFormat = savedFormat;
        document.getElementById('scanFormat').value = savedFormat;
    }
}

function openSettings() {
    document.getElementById('settingsModal').style.display = 'block';
}

function closeSettings() {
    document.getElementById('settingsModal').style.display = 'none';
}

// ============ Utility Functions ============
function isUrl(text) {
    return /^https?:\/\/.+/.test(text);
}

function escapeHtml(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}

function showToast(msg) {
    const toast = document.getElementById('toast');
    toast.textContent = msg;
    toast.style.display = 'block';
    clearTimeout(toast._timeout);
    toast._timeout = setTimeout(() => { toast.style.display = 'none'; }, 2000);
}

function playBeep() {
    try {
        const ctx = new (window.AudioContext || window.webkitAudioContext)();
        const oscillator = ctx.createOscillator();
        const gain = ctx.createGain();
        oscillator.connect(gain);
        gain.connect(ctx.destination);
        oscillator.frequency.value = 880;
        oscillator.type = 'sine';
        gain.gain.value = 0.3;
        oscillator.start(ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.15);
        oscillator.stop(ctx.currentTime + 0.15);
    } catch {
        // Audio not available
    }
}

// ============ PWA Registration ============
if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
        navigator.serviceWorker.register('sw.js').catch(() => {});
    });
}
